### ISSUE TITLE
hybris-10 XZ3 glitch on screen while swiping or unlocking

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#150] opened 2021-06-27 16:46 UTC
A thin horizontal line appears on the screen, very close to the top mostly, while unlocking or swiping screen for about a second or less, also updating screen content feels a bit sluggish.

**Comment by pagism** [comment] 2021-06-27 17:40
somehow it got fixed itself, i cannot see it any.more

**Comment by rinigus** [comment] 2021-06-27 17:40
Thin horizontal line - no idea where is this coming from. I don't have that on my devices (XZ2 & XZ2c). Let's see if others report similar. But does make wonder whether we have some init issue for the screen.

For me, sluggishness is while in lipstick - see https://github.com/sailfishos-sony-tama/main/issues/143 . In the apps all is fine, as far as I can tell.

**Comment by pagism** [comment] 2021-06-27 17:48
well, i was a bit fast responding, it appears again, especially when unlocking the screen, it might be related to #143 issue. where in this case it appers as a thin band of broken pixels horizontally across ghe screen, close to the top

**Comment by rinigus** [comment] 2021-06-27 18:31
Just checking - did you install latest stock Android by Sony before flashing?

While I do have slower response, I don't see any glitches on the screen. Anything interesting in journal or logcat? Although, hard to define "interesting"

**Comment by pagism** [comment] 2021-06-27 18:47
I had lots of issues in the past with my xz3, the last month of so it was running stock Android 10 without any issues, possibly not the very latest version as Emma's provided list is restricted, most likely 52.1.A.3.92

**Comment by rinigus** [comment] 2021-06-27 18:57
That should be at least something - not just jumping from AOSP9 to AOSP10. 

Screen glitches - do you see that in the apps as well? Or only in Lipstick?

**Comment by pagism** [comment] 2021-06-27 19:04
I think it's lipstick, I tried the browser and storeman, no such glitches

**Comment by rinigus** [comment] 2021-06-27 19:22
Maybe this glitch is caused by 4K display, hard to say. Let's see if we get any idea on how to fix #143 and whether it will help with this case.

**Comment by rinigus** [comment] 2021-06-28 20:02
Can't see anything that I wouldn't have in dmesg or logcat (hopefully haven't missed it). So, nothing yet ...

**Comment by pagism** [comment] 2021-06-29 14:59
Here is an example, unlocking the device and swiping the lock screen:

https://user-images.githubusercontent.com/59111727/123820955-e6280600-d8f2-11eb-85f5-1dca00962575.mp4

**Comment by rinigus** [comment] 2021-06-29 17:26
Thank you very much!

**Comment by rinigus** [comment] 2021-06-30 06:52
Haven't got in touch with others yet, but please try

```
# as root
cd /sys/class/devfreq/soc:qcom,gpubw/
```

Check what is current governor, frequencies: cur_freq, governor using `cat`

Change governor to `performance`:
```
echo performance > governor
```

The latter command doesn't always work via ssh. You may have to run it from the terminal on your phone.

Test if the lines are still there and whether your lipstick transitions are smooth. Reboot after testing to restore governor settings.

**Comment by pagism** [comment] 2021-06-30 09:20
currently I have the impression it holds charging really well, the current values for gov and freq are:
```
# cat governor 
bw_vbif
# cat cur_freq 
381
```
Changing gov to performance, I had to use quotes e.g.
```
[root@XperiaXZ3 soc:qcom,gpubw]# echo 'performance' > governor
```
It seems to work, no more glitches, here is the output of gov and freq:
```
# cat governor 
performance
# cat cur_freq 
6881
```
rebooting restores previous value, i.e. `bw_vbif`
thanks

**Comment by rinigus** [comment] 2021-06-30 10:15
OK, do I read it right - when set to performance, you had no strange lines on transitions AND lipstick was as fast as it should be?

I have a feeling that we will be able to get some better battery balance and GPU performance by changing devfreq governors and  their parameters. It looks like CPU frequencies are too high for no reason at some conditions. But those are separate issues and I am looking into that. At least, screen glitch is gone and that is very good!

**Comment by pagism** [comment] 2021-06-30 10:24
correct, no strange lines and smooth transitions. I guess there is some tuning work to be done here.
Here is few data I gathered:
```
name: soc:qcom,gpubw
available_frequencies 
381 572 762 1144 1720 2086 2597 2929 3879 4943 5931 6881
available_governors 
compute mem_latency bw_hwmon vidc-ar50-llcc vidc-ar50-ddr msm-vidc-llcc msm-vidc-ddr gpubw_mon bw_vbif msm-adreno-tz userspace powersave performance simple_ondemand
```
and for comparison from xa2:
```
available_frequencies 
0 381 572 762 1144 1571 2086 2597 2929 3879 4943 5161
available_governors 
spdm_bw_hyp mem_latency bw_hwmon venus-ddr-gov msm-vidc-vmem+ msm-vidc-vmem msm-vidc-ddr bw_vbif gpubw_mon cpufreq msm-adreno-tz userspace powersave performance simple_ondemand
```

**Comment by rinigus** [comment] 2021-06-30 16:55
Nice! So, we can probably close it here and continue discussion at #143 regarding slow framerate and glitches as well as battery life aspect at #154 . This is something I am working on now and hopefully can get it better soon

**Comment by rinigus** [comment] 2021-07-13 17:32
I presume we can close it now with the requirement of zgovernor. Please reopen if you observe again on recent or future releases

**Closed as completed by rinigus** 2021-07-13 17:32 UTC
Labels: hybris-10
