### ISSUE TITLE
XZ2 H8266 Sailfish OS 4.5.0.16 Bluetooth not working

### ISSUE THREAD

**Issue by VZuyev** [sailfishos-sony-tama/main#196] opened 2023-02-13 09:41 UTC
Bluetooth not working.
systemctl restart bluetooth (up to three times)
Bluetooth working.
reboot
Bluetooth not working.
...

**Comment by rinigus** [comment] 2023-02-13 15:32
This report was done before I released SFOS update, so I have no idea what did you use for update. Over here, on XZ2 single sim, BT looks to be working. Will release update officially shortly, please make OTA as expected and test again. I tested using GUI switches in Settings

**Comment by VZuyev** [comment] 2023-02-13 16:12
1. Installed today https://github.com/sailfishos-sony-tama/main/releases/download/4.4.0.58/Sailfish_OS-4.4.0.58-h8266-0.5.0.1.zip
2. Updated to 4.5.0.16 today according to this instruction https://github.com/sailfishos-sony-tama/main#over-the-air-updates-ota

**Comment by rinigus** [comment] 2023-02-13 16:42
OK, you skipped one 4.4 release, but I don't know if it is of any importance. Have you tried to start bluetooth from GUI - without touching any systemd services manually? Has bluetooth worked for you on XZ2 SFOS earlier?

I will soon upload 4.5 SFOS images as well. If you are flashing anyway, you could try those too

**Comment by VZuyev** [comment] 2023-02-13 17:01
Bluetooth worked on 4.4.0.58 and 4.4.0.72.
1. Today installed 4.4.0.58, updated to 4.4.0.72, updated to 4.5.0.16. Bluetooth not worked. Yes, I have tried to start bluetooth from GUI - without touching any systemd services manually.
2. Today installed 4.4.0.58, updated to 4.5.0.16. Bluetooth not working. Yes, I have tried to start bluetooth from GUI - without touching any systemd services manually.

**Comment by rinigus** [comment] 2023-02-13 18:06
I cannot reproduce it on h8216 (XZ2) and h8324 (XZ2c). On my devices bluetooth starts, connects, and allows to use bt device during a call.

**Comment by VZuyev** [comment] 2023-02-13 18:15
https://forum.sailfishos.org/t/4-5-0-16-xperia-xa2-plus-bluetooth-not-available/14349
Settings-> Utils-> Bluetooth Restart helps now.

**Comment by VZuyev** [comment] 2023-02-13 19:11
Installed 4.5.0.16 https://github.com/sailfishos-sony-tama/main/releases/download/4.5.0.16/Sailfish_OS-4.5.0.16-h8266-0.5.0.1.zip
Bluetooth not working.
Settings->Utils->Bluetooth Restart helps.

**Comment by rinigus** [comment] 2023-02-13 19:20
> Settings->Utils->Bluetooth Restart helps.

please explain. Does the restart via Utils makes it possible to use BT? After that all works as it should?

**Comment by VZuyev** [comment] 2023-02-13 19:24
Yes. Restart via Utils makes it possible to use BT. After reboot BT doesn't work again.

**Comment by VZuyev** [comment] 2023-02-13 19:29
Please correct flash-on-windows.bat.

[flash-on-windows.zip](https://github.com/sailfishos-sony-tama/main/files/10725592/flash-on-windows.zip)

Corrected fragment:

:no_error_serialnumbers

for %%d in ( %serialnumbers% ) do (
  set fastbootcmd=%fastbootcmd_no_device% -s %%d
  @call :getvar product
  findstr /R ":: H8266" %tmpflashfile% >NUL 2>NUL
  if not errorlevel 1 (
    call :new_product_found %%d
  )
)

**Comment by rinigus** [comment] 2023-02-13 19:35
Please submit PR with the change. Then I can attribute it to you. File to patch is https://github.com/sailfishos-sony-tama/droid-config-sony-tama-pie/blob/hybris-10/sparse/boot/flash-on-windows.bat

**Comment by VZuyev** [comment] 2023-02-14 11:22
https://github.com/sailfishos-sony-tama/droid-config-sony-tama-pie/blob/hybris-10/sparse/boot/flash-on-windows.bat
Everything seems to be correct in this file.

Fragment from file https://github.com/sailfishos-sony-tama/droid-config-sony-tama-pie/blob/hybris-10/sparse/boot/flash-on-windows.bat:

:no_error_serialnumbers

for %%d in ( %serialnumbers% ) do (
  set fastbootcmd=%fastbootcmd_no_device% -s %%d
  @call :getvar product
  findstr /R "@DEVICES@" %tmpflashfile% >NUL 2>NUL
  if not errorlevel 1 (
    call :new_product_found %%d
  )
)

Fragment from not working file flash-on-windows.bat Sailfish_OS-4.5.0.16-h8266-0.5.0.1:

:no_error_serialnumbers

for %%d in ( %serialnumbers% ) do (
  set fastbootcmd=%fastbootcmd_no_device% -s %%d
  @call :getvar product
  findstr /R ":: H8266
:: H8266" %tmpflashfile% >NUL 2>NUL
  if not errorlevel 1 (
    call :new_product_found %%d
  )
)

**Comment by rinigus** [comment] 2023-02-14 18:52
Closing as original issue seems to be resolved.

**Closed as completed by rinigus** 2023-02-14 18:52 UTC
