### ISSUE TITLE
jolla-camera crashes after update to Suomenlinna

### ISSUE THREAD

**Issue by LutzAdam** [sailfishos-sony-tama/main#179] opened 2021-11-15 16:43 UTC
In the terminal-app enter:
jolla-camera
    [D] unknown:0 - Using Wayland-EGL
    jolla-camera: /usr/share/droidmedia/hybris.c:53: __resolve_sym: Zusicherung >>ptr != NULL<< nicht erfüllt.
             _in english maybe:  assertion ... not satisfied._
    Aborted (core dumped)

uname -a
    Linux XperiaXA2Ultra 4.4.194 #1 SMP PREEMPT Mon Oct 25  21:59:00 UTC 2021 aarch GNU/Linux
    
Sailfish OS Suomenlinna  Version 4.3.0.12

Reproducibility: always

**Comment by rinigus** [comment] 2021-11-15 16:47
The work on 4.3 update for Tama has not started even due to my engagement with other projects. As a result, 4.3.0.12 has not been released for Tama. So, it is expected that things get broken when you try to update some components to the next release. Closing as it is not a bug

**Closed as completed by rinigus** 2021-11-15 16:47 UTC

**Comment by LutzAdam** [comment] 2021-11-15 17:04
I did NOT try to update some components to the next release. The release 4.3.0.12 was offered 1 or 2 weeks ago as installable   through the "Einstellungen / settings" > "Aktualisierungen für Sailfish OS / updates for ..."

**Comment by lal883** [comment] 2021-11-15 17:08
Isn't Xperia XA2 Ultra an officially supported device? Definitely not Tama. Guess you might have better luck on https://forum.sailfishos.org/
